# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data import Data  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class GetGeoDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_id: str=None, vehicle_id: str=None, time: datetime=None, latitude: str=None, longitude: str=None, altimeter: str=None):  # noqa: E501
        """GetGeoDataResponse - a model defined in Swagger

        :param data_id: The data_id of this GetGeoDataResponse.  # noqa: E501
        :type data_id: str
        :param vehicle_id: The vehicle_id of this GetGeoDataResponse.  # noqa: E501
        :type vehicle_id: str
        :param time: The time of this GetGeoDataResponse.  # noqa: E501
        :type time: datetime
        :param latitude: The latitude of this GetGeoDataResponse.  # noqa: E501
        :type latitude: str
        :param longitude: The longitude of this GetGeoDataResponse.  # noqa: E501
        :type longitude: str
        :param altimeter: The altimeter of this GetGeoDataResponse.  # noqa: E501
        :type altimeter: str
        """
        self.swagger_types = {
            'data_id': str,
            'vehicle_id': str,
            'time': datetime,
            'latitude': str,
            'longitude': str,
            'altimeter': str
        }

        self.attribute_map = {
            'data_id': 'dataId',
            'vehicle_id': 'vehicleId',
            'time': 'time',
            'latitude': 'latitude',
            'longitude': 'longitude',
            'altimeter': 'altimeter'
        }
        self._data_id = data_id
        self._vehicle_id = vehicle_id
        self._time = time
        self._latitude = latitude
        self._longitude = longitude
        self._altimeter = altimeter

    @classmethod
    def from_dict(cls, dikt) -> 'GetGeoDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetGeoDataResponse of this GetGeoDataResponse.  # noqa: E501
        :rtype: GetGeoDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_id(self) -> str:
        """Gets the data_id of this GetGeoDataResponse.


        :return: The data_id of this GetGeoDataResponse.
        :rtype: str
        """
        return self._data_id

    @data_id.setter
    def data_id(self, data_id: str):
        """Sets the data_id of this GetGeoDataResponse.


        :param data_id: The data_id of this GetGeoDataResponse.
        :type data_id: str
        """
        if data_id is None:
            raise ValueError("Invalid value for `data_id`, must not be `None`")  # noqa: E501

        self._data_id = data_id

    @property
    def vehicle_id(self) -> str:
        """Gets the vehicle_id of this GetGeoDataResponse.


        :return: The vehicle_id of this GetGeoDataResponse.
        :rtype: str
        """
        return self._vehicle_id

    @vehicle_id.setter
    def vehicle_id(self, vehicle_id: str):
        """Sets the vehicle_id of this GetGeoDataResponse.


        :param vehicle_id: The vehicle_id of this GetGeoDataResponse.
        :type vehicle_id: str
        """
        if vehicle_id is None:
            raise ValueError("Invalid value for `vehicle_id`, must not be `None`")  # noqa: E501

        self._vehicle_id = vehicle_id

    @property
    def time(self) -> datetime:
        """Gets the time of this GetGeoDataResponse.

        Data collection date  # noqa: E501

        :return: The time of this GetGeoDataResponse.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this GetGeoDataResponse.

        Data collection date  # noqa: E501

        :param time: The time of this GetGeoDataResponse.
        :type time: datetime
        """
        if time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    @property
    def latitude(self) -> str:
        """Gets the latitude of this GetGeoDataResponse.


        :return: The latitude of this GetGeoDataResponse.
        :rtype: str
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: str):
        """Sets the latitude of this GetGeoDataResponse.


        :param latitude: The latitude of this GetGeoDataResponse.
        :type latitude: str
        """
        if latitude is None:
            raise ValueError("Invalid value for `latitude`, must not be `None`")  # noqa: E501

        self._latitude = latitude

    @property
    def longitude(self) -> str:
        """Gets the longitude of this GetGeoDataResponse.


        :return: The longitude of this GetGeoDataResponse.
        :rtype: str
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: str):
        """Sets the longitude of this GetGeoDataResponse.


        :param longitude: The longitude of this GetGeoDataResponse.
        :type longitude: str
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    @property
    def altimeter(self) -> str:
        """Gets the altimeter of this GetGeoDataResponse.


        :return: The altimeter of this GetGeoDataResponse.
        :rtype: str
        """
        return self._altimeter

    @altimeter.setter
    def altimeter(self, altimeter: str):
        """Sets the altimeter of this GetGeoDataResponse.


        :param altimeter: The altimeter of this GetGeoDataResponse.
        :type altimeter: str
        """
        if altimeter is None:
            raise ValueError("Invalid value for `altimeter`, must not be `None`")  # noqa: E501

        self._altimeter = altimeter
