# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data import Data  # noqa: F401,E501
from swagger_server.models.enum_sensor_type import EnumSensorType  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class GetTelemetryDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_id: str=None, vehicle_id: str=None, time: datetime=None, sensor_type: EnumSensorType=None, value: float=None):  # noqa: E501
        """GetTelemetryDataResponse - a model defined in Swagger

        :param data_id: The data_id of this GetTelemetryDataResponse.  # noqa: E501
        :type data_id: str
        :param vehicle_id: The vehicle_id of this GetTelemetryDataResponse.  # noqa: E501
        :type vehicle_id: str
        :param time: The time of this GetTelemetryDataResponse.  # noqa: E501
        :type time: datetime
        :param sensor_type: The sensor_type of this GetTelemetryDataResponse.  # noqa: E501
        :type sensor_type: EnumSensorType
        :param value: The value of this GetTelemetryDataResponse.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'data_id': str,
            'vehicle_id': str,
            'time': datetime,
            'sensor_type': EnumSensorType,
            'value': float
        }

        self.attribute_map = {
            'data_id': 'dataId',
            'vehicle_id': 'vehicleId',
            'time': 'time',
            'sensor_type': 'sensor_type',
            'value': 'value'
        }
        self._data_id = data_id
        self._vehicle_id = vehicle_id
        self._time = time
        self._sensor_type = sensor_type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'GetTelemetryDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetTelemetryDataResponse of this GetTelemetryDataResponse.  # noqa: E501
        :rtype: GetTelemetryDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_id(self) -> str:
        """Gets the data_id of this GetTelemetryDataResponse.


        :return: The data_id of this GetTelemetryDataResponse.
        :rtype: str
        """
        return self._data_id

    @data_id.setter
    def data_id(self, data_id: str):
        """Sets the data_id of this GetTelemetryDataResponse.


        :param data_id: The data_id of this GetTelemetryDataResponse.
        :type data_id: str
        """
        if data_id is None:
            raise ValueError("Invalid value for `data_id`, must not be `None`")  # noqa: E501

        self._data_id = data_id

    @property
    def vehicle_id(self) -> str:
        """Gets the vehicle_id of this GetTelemetryDataResponse.


        :return: The vehicle_id of this GetTelemetryDataResponse.
        :rtype: str
        """
        return self._vehicle_id

    @vehicle_id.setter
    def vehicle_id(self, vehicle_id: str):
        """Sets the vehicle_id of this GetTelemetryDataResponse.


        :param vehicle_id: The vehicle_id of this GetTelemetryDataResponse.
        :type vehicle_id: str
        """
        if vehicle_id is None:
            raise ValueError("Invalid value for `vehicle_id`, must not be `None`")  # noqa: E501

        self._vehicle_id = vehicle_id

    @property
    def time(self) -> datetime:
        """Gets the time of this GetTelemetryDataResponse.

        Data collection date  # noqa: E501

        :return: The time of this GetTelemetryDataResponse.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this GetTelemetryDataResponse.

        Data collection date  # noqa: E501

        :param time: The time of this GetTelemetryDataResponse.
        :type time: datetime
        """
        if time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    @property
    def sensor_type(self) -> EnumSensorType:
        """Gets the sensor_type of this GetTelemetryDataResponse.


        :return: The sensor_type of this GetTelemetryDataResponse.
        :rtype: EnumSensorType
        """
        return self._sensor_type

    @sensor_type.setter
    def sensor_type(self, sensor_type: EnumSensorType):
        """Sets the sensor_type of this GetTelemetryDataResponse.


        :param sensor_type: The sensor_type of this GetTelemetryDataResponse.
        :type sensor_type: EnumSensorType
        """
        if sensor_type is None:
            raise ValueError("Invalid value for `sensor_type`, must not be `None`")  # noqa: E501

        self._sensor_type = sensor_type

    @property
    def value(self) -> float:
        """Gets the value of this GetTelemetryDataResponse.

        Sensor value  # noqa: E501

        :return: The value of this GetTelemetryDataResponse.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this GetTelemetryDataResponse.

        Sensor value  # noqa: E501

        :param value: The value of this GetTelemetryDataResponse.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
