"""making changes

Revision ID: 047e88be2f58
Revises: b0f7ef0de383
Create Date: 2023-03-02 13:57:17.557658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047e88be2f58'
down_revision = 'b0f7ef0de383'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
