"""making changes

Revision ID: 1e801f3b052a
Revises: 4a2338e0e2ec
Create Date: 2023-03-02 14:34:27.412741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e801f3b052a'
down_revision = '4a2338e0e2ec'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
