"""making changes

Revision ID: 3b8bb97040f3
Revises: 71f48b169dcf
Create Date: 2023-03-02 14:47:49.896031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8bb97040f3'
down_revision = '71f48b169dcf'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
