"""making changes

Revision ID: 401be1f18c39
Revises: f718ecc7a590
Create Date: 2023-03-02 14:48:20.914084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401be1f18c39'
down_revision = 'f718ecc7a590'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
