"""making changes

Revision ID: 407070460874
Revises: 92eefda95fa3
Create Date: 2023-03-02 14:03:34.018575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407070460874'
down_revision = '92eefda95fa3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
