"""making changes

Revision ID: 43daaae06731
Revises: bb9f017cdfff
Create Date: 2023-03-02 15:34:47.002493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43daaae06731'
down_revision = 'bb9f017cdfff'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
