"""making changes

Revision ID: 4a2338e0e2ec
Revises: 53355fca8cc2
Create Date: 2023-03-02 14:34:24.820687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2338e0e2ec'
down_revision = '53355fca8cc2'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
