"""making changes

Revision ID: 53355fca8cc2
Revises: 5a20c04c0ca9
Create Date: 2023-03-02 14:28:08.040136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53355fca8cc2'
down_revision = '5a20c04c0ca9'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
