"""making changes

Revision ID: 53431950ca6f
Revises: aa74307e108a
Create Date: 2023-03-02 15:20:34.046610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53431950ca6f'
down_revision = 'aa74307e108a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
