"""making changes

Revision ID: 570eebe2ca48
Revises: 53431950ca6f
Create Date: 2023-03-02 15:20:50.821308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570eebe2ca48'
down_revision = '53431950ca6f'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
