"""making changes

Revision ID: 592c9e30650e
Revises: 
Create Date: 2023-03-02 13:44:19.948694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '592c9e30650e'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('data_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.DateTime(timezone=32), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_table('geo_data',
    sa.Column('data_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('latitude', sa.String(length=32), nullable=False),
    sa.Column('longitude', sa.String(length=32), nullable=False),
    sa.Column('altimeter', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data.data_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_table('telemetry_data',
    sa.Column('data_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sensor_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['data.data_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_data')
    op.drop_table('geo_data')
    op.drop_table('data')
    # ### end Alembic commands ###
