"""making changes

Revision ID: 5a20c04c0ca9
Revises: f5414df138af
Create Date: 2023-03-02 14:28:05.571423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a20c04c0ca9'
down_revision = 'f5414df138af'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
