"""making changes

Revision ID: 71f48b169dcf
Revises: db23f07ef396
Create Date: 2023-03-02 14:38:12.021247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f48b169dcf'
down_revision = 'db23f07ef396'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
