"""making changes

Revision ID: 7a6358ad99dc
Revises: d4ebe6b67f0e
Create Date: 2023-03-02 15:40:30.966018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6358ad99dc'
down_revision = 'd4ebe6b67f0e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
