"""making changes

Revision ID: 7c1803a45517
Revises: f11b0b891186
Create Date: 2023-03-02 15:36:25.467496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1803a45517'
down_revision = 'f11b0b891186'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
