"""making changes

Revision ID: 7c6d9eb3914d
Revises: 9300c2c21a04
Create Date: 2023-03-02 15:50:50.641412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6d9eb3914d'
down_revision = '9300c2c21a04'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
