"""making changes

Revision ID: 89c88cfcf7c4
Revises: 7c6d9eb3914d
Create Date: 2023-03-02 15:50:57.157576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c88cfcf7c4'
down_revision = '7c6d9eb3914d'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
