"""making changes

Revision ID: 8fe30926347a
Revises: e72158037638
Create Date: 2023-03-02 15:07:45.860873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fe30926347a'
down_revision = 'e72158037638'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('time', sa.DateTime(timezone=32), nullable=False))
    op.drop_column('data', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('data', 'time')
    # ### end Alembic commands ###
