"""making changes

Revision ID: 92eefda95fa3
Revises: 047e88be2f58
Create Date: 2023-03-02 13:59:18.192690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eefda95fa3'
down_revision = '047e88be2f58'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
