"""making changes

Revision ID: 9300c2c21a04
Revises: ce0d1ea84412
Create Date: 2023-03-02 15:49:30.481404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9300c2c21a04'
down_revision = 'ce0d1ea84412'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
