"""making changes

Revision ID: aa74307e108a
Revises: bba25849e76c
Create Date: 2023-03-02 15:17:37.178310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa74307e108a'
down_revision = 'bba25849e76c'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
