"""making changes

Revision ID: b0f7ef0de383
Revises: c903f8968653
Create Date: 2023-03-02 13:57:14.631098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f7ef0de383'
down_revision = 'c903f8968653'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
