"""making changes

Revision ID: b9e2a2b5360f
Revises: 8fe30926347a
Create Date: 2023-03-02 15:07:51.376023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e2a2b5360f'
down_revision = '8fe30926347a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
