"""making changes

Revision ID: bb9f017cdfff
Revises: 570eebe2ca48
Create Date: 2023-03-02 15:34:00.163812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9f017cdfff'
down_revision = '570eebe2ca48'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
