"""making changes

Revision ID: bba25849e76c
Revises: ef96ef768472
Create Date: 2023-03-02 15:17:31.738840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba25849e76c'
down_revision = 'ef96ef768472'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
