"""making changes

Revision ID: c903f8968653
Revises: 592c9e30650e
Create Date: 2023-03-02 13:44:23.092824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c903f8968653'
down_revision = '592c9e30650e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
