"""making changes

Revision ID: ce0d1ea84412
Revises: 7a6358ad99dc
Create Date: 2023-03-02 15:46:36.536282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0d1ea84412'
down_revision = '7a6358ad99dc'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
