"""making changes

Revision ID: d4ebe6b67f0e
Revises: 7c1803a45517
Create Date: 2023-03-02 15:36:32.006457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ebe6b67f0e'
down_revision = '7c1803a45517'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
