"""making changes

Revision ID: da538f47bc15
Revises: 43daaae06731
Create Date: 2023-03-02 15:35:13.371407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da538f47bc15'
down_revision = '43daaae06731'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
