"""making changes

Revision ID: db23f07ef396
Revises: 1e801f3b052a
Create Date: 2023-03-02 14:38:05.508207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db23f07ef396'
down_revision = '1e801f3b052a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
