"""making changes

Revision ID: ef96ef768472
Revises: fc838ae61f17
Create Date: 2023-03-02 15:14:52.853165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef96ef768472'
down_revision = 'fc838ae61f17'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
