"""making changes

Revision ID: f11b0b891186
Revises: da538f47bc15
Create Date: 2023-03-02 15:35:45.325777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11b0b891186'
down_revision = 'da538f47bc15'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
