"""making changes

Revision ID: f718ecc7a590
Revises: 3b8bb97040f3
Create Date: 2023-03-02 14:48:05.562450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f718ecc7a590'
down_revision = '3b8bb97040f3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
