"""making changes

Revision ID: fc838ae61f17
Revises: b9e2a2b5360f
Create Date: 2023-03-02 15:11:23.479211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc838ae61f17'
down_revision = 'b9e2a2b5360f'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
